using System.Reflection;
using System.Runtime.InteropServices;
using System.Security;

[assembly: AssemblyTitle("Abc.Xyz.Workflow.Test")]
[assembly: AssemblyDescription("Generated by DynamicsCrm.DevKit - 2.13.33 - https://github.com/phuocle/Dynamics-Crm-DevKit")]
#if DEBUG
[assembly: AssemblyConfiguration("Debug")]
#else
[assembly: AssemblyConfiguration("Release")]
#endif
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("Abc.Xyz.Workflow.Test")]
[assembly: AssemblyCopyright("Copyright © 2022")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("en")]
[assembly: SecurityRules(SecurityRuleSet.Level2)]
[assembly: ComVisible(false)]
[assembly: Guid("20f1a72a-db84-4a63-8642-bade14179cb7")]
[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyFileVersion("1.0.0.0")]
